css-layout-classes - Cynthia Huynh
HuynhCynthia/c0123-code-solutions pull request #17
Opened 2023-01-27 01:23 UTC by HuynhCynthia

![Screen Shot 2023-01-26 at 5 21 02 PM](https://user-images.githubusercontent.com/115051720/214988073-75843b88-20d9-44e7-b415-bba2ec6a7337.png)

2023-01-27 18:37 UTC, shawnkost requested changes
Hey Cynthia! Some changes requested below! Make sure only `column` is a child of a `row` and you're not nesting `row` inside of a `column`. Also make sure each of the different columns have their own selector, and you're applying `flex-basis` based off of the amount of width they should get. I recommend reviewing the exercise instructions to try and get a better understanding of how the separation between rows & columns work. 

Please reach out with any questions!

2023-01-27 18:37 UTC, shawnkost commented on css-layout-classes/index.html
> +        <div class="row-summary">
A `row` should never come after a `column`. The structure should be along these lines `container > row > column`. This `div` isn't necessary, because you already have a `column` div above this, and this is all apart of one `column`

2023-01-27 18:37 UTC, shawnkost commented on css-layout-classes/index.html
> +        </div>
Similiar to my note above ^ . This `row-summary` shouldn't come after a `column`. Since all of this content is apart of one `column`, it should all be inside your `<div class="column-summary">`

2023-01-27 18:37 UTC, shawnkost commented on css-layout-classes/styles.css
> +  width: 100%;
Remove this `width: 100%`

2023-01-27 18:37 UTC, shawnkost commented on css-layout-classes/styles.css
> +
You should have multiple column selectors just like what you're doing here with `.column-summary`. So for example, here's how I would handle the columns for the 4 characters in a row.

`.four-characters {
flex-basis: 25%
}`.

2023-01-30 17:32 UTC, shawnkost requested changes
Hey Cynthia! A few changes requested here. Make sure you are using class names related to `column` to showcase how much space you expect each column to take up. This makes this a lot more readable and you can understand exactly what it does by looking at it. Also, make sure each of your `column` related classes have a `flex-basis` property applied to them telling them how much space to take up.

2023-01-30 17:32 UTC, shawnkost commented on css-layout-classes/styles.css
> +  width: 100%;
Instead of `width: 100%` this should be `flex-basis: calc(200% / 3)` because this column should be taking up 2/3rds of the web page

2023-01-30 17:32 UTC, shawnkost commented on css-layout-classes/styles.css
> +  width: 100%;
Instead of `width: 100%` this should be `flex-basis: calc(200% / 3)` because this column should be taking up 2/3rds of the web page

2023-01-30 17:32 UTC, shawnkost commented on css-layout-classes/index.html
> +      <div class="dk-bio">
I would add another class to this like `column-two-thirds` to symbolize how much space this column will take up. Then you can add my note below about `flex-basis` to this class instead of `dk-bio`

2023-01-30 17:32 UTC, shawnkost commented on css-layout-classes/index.html
> +      <div class="dk-image">
Add another class like `column-third` to showcase how much space this column will take up & apply `flex-basis` based off of that

2023-01-30 17:32 UTC, shawnkost commented on css-layout-classes/index.html
> +      <div class="mario-image">
See note above about `column-third` ^

2023-01-30 17:32 UTC, shawnkost commented on css-layout-classes/index.html
> +      <div class="mario-bio">
See note above about `column-two-thirds` ^

2023-01-30 17:32 UTC, shawnkost commented on css-layout-classes/styles.css
> +}
You should have css selectors for `column-third` or in your case how it's currently named `mario-image` and apply a `flex-basis` property based off of the amount of space you'd like it to take up. View my notes above ^

2023-01-30 21:51 UTC, JenBowman1 approved these changes
👍

2023-01-30 22:49 UTC, merged