practicing process.argv in Node.js - Cynthia Huynh
HuynhCynthia/c0123-code-solutions pull request #71
Opened 2023-03-14 23:03 UTC by HuynhCynthia

<img width="1102" alt="Screen Shot 2023-03-14 at 4 00 59 PM" src="https://user-images.githubusercontent.com/115051720/225161153-c1f2de92-967c-4cdb-a069-e890849b3f6d.png">

2023-03-14 23:06 UTC, RobertGardner requested changes
Did you forget to push? Several of these files are empty.

2023-03-14 23:24 UTC, HuynhCynthia commented
<img width="1027" alt="Screen Shot 2023-03-14 at 4 10 21 PM" src="https://user-images.githubusercontent.com/115051720/225163802-f597a885-f7ae-4122-9b42-d4d57163b14b.png">
<img width="1094" alt="Screen Shot 2023-03-14 at 4 10 45 PM" src="https://user-images.githubusercontent.com/115051720/225162625-e52f3bb0-d88f-4a73-aebe-cf35749fd108.png">

2023-03-14 23:27 UTC, HuynhCynthia commented
> Did you forget to push? Several of these files are empty.

worse I deleted my code and didn't retype them when I pushed. Pushed again.

2023-03-15 00:05 UTC, RobertGardner approved these changes

2023-03-15 03:31 UTC, merged